### ISSUE TITLE
Program nie istnieje.

### ISSUE THREAD

**Issue by dzejus** [workonfire/Klementynka#1]
Chciałbym złożyć skargę, iż zamieścił Pan program, który (jak sam Pan twierdzi) nie istnieje. Jak w takim razie ma działać, skoro kod nie został w ogóle napisany? Chyba wehikuł czasu zadziałał i to aż za dobrze.

**Comment by workonfire** [comment]
#wyobraznia. W wyobraźni możliwe jest wszystko, Pan jak widać tego nie rozumie.

Program istnieje, ale tylko w wyobraźni.
